apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: kaniko
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Build container image with Kaniko
        uses: cloudbees-io/kaniko@CBP-6772-2
        with:
          destination: docker.io/rthomascb/docker-demo:0.0.1-SNAPSHOT
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
