apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - corinne
  corinne:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 8c38c97a-87ec-11ef-9f27-42010a83ae47,015d04e8-5bcb-11eb-93be-42010a83aee8, 5ea63edb-9b14-4f19-b423-7ae7bd92de9b
      disallowLaunchByUser: false
      instructions: ddddd
