apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      boo:
        type: boolean
        default: true
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - corinne
  corinne:
    with:
      approvers: 8c38c97a-87ec-11ef-9f27-42010a83ae47,015d04e8-5bcb-11eb-93be-42010a83aee8
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        boolParam:
          type: boolean
          default: false
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
