apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      stringParamTrigger:
        type: string
        default: stringParamTriggerDefaultValue
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs: approvalJob
  approvalJob:
    with:
      approvers: ""
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      instructions: ddddd
      approvalInputs: |
        stringParamApproval:
          type: string
          default: stringParamApprovalDefaultValue
          required: true
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
