apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      cxcxcx:
        type: string
  workflow_call:
    inputs:
      d1:
        type: number
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - job2
  approvalJob:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 8c38c97a-87ec-11ef-9f27-42010a83ae47,015d04e8-5bcb-11eb-93be-42010a83aee8, 5ea63edb-9b14-4f19-b423-7ae7bd92de9b
      disallowLaunchByUser: false
      instructions: ddddd
      approvalInputValues:
        string1:
          type: string
          required: true
        string2:
          type: string
          required: true
  job2:
    needs: approvalJob
    environment: ""
    steps:
      - name: ewew
        uses: cloudbees-io/s3-upload-object@v1
        run: ""
        with:
          bucket-name: ssss
          file-path: s
          s3-path: s
        shell: ""
        kind: build
