apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      Name:
        type: string
        required: true
        description: Description 1
      Version:
        type: number
        required: true
        description: Description 2
      Release_type:
        type: choice
        options:
          - Standard
          - Hotfix
        default: Standard
        required: true
        description: Description 4
      Smart_deploy:
        type: boolean
        default: true
        required: true
        description: Description 3
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - e
  e:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 76bb48b2-a920-11ee-bb83-42010a83ae92,85ff1b0c-1ae1-11ec-af3a-42010a83aecb,fd587892-cacd-11eb-9ec3-42010a83ae11,e3d34af6-efa2-11eb-9d3b-42010a83ae11,015d04e8-5bcb-11eb-93be-42010a83aee8
      disallowLaunchByUser: false
      instruction: ""
