apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  name:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: step1
        run: echo "hello world"
        shell: sh
