apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      num:
        type: number
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  approvalJob:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: []
      instruction: ""
      disallowLaunchByUser: false
    needs: build
  approval2:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: ckrych@cloudbees.com
      instruction: do sth
      disallowLaunchByUser: false
